version: 2.1
orbs:
  slack: circleci/slack@3.4.2
aliases:
    - &ssh-fingerprint
      fingerprints:
        - “ab:f2:26:09:86:b8:d3:28:be:bd:5b:86:7d:70:3e:ce”
    - &filter-only-master-and-release
      branches:
        only:
          - master
          - /release-.*/
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/Tavla

    steps:
      - checkout
      - add_ssh_keys: *ssh-fingerprint
      - run: npm ci
      - run: npm test
      - run: npm run lint

  deploy:
    docker:
      - image: circleci/node:10

    working_directory: ~/Tavla

    steps:
      - checkout
      - add_ssh_keys: *ssh-fingerprint
      - run: npm ci
      - run:
          name: Deploy web
          command: npm run deploy:prod --token=$FIREBASE_TOKEN --non-interactive
      - slack/status
  deploy-staging:
    docker:
      - image: circleci/node:10

    working_directory: ~/Tavla

    steps:
      - checkout
      - add_ssh_keys: *ssh-fingerprint
      - run: npm ci
      - run:
          name: Deploy web staging
          command: npm run deploy:staging --token=$FIREBASE_TOKEN --non-interactive
      - slack/status
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-staging:
          filters:
              branches:
                only:
                  - master
          requires:
              - build
      - prod-approval:
          requires:
              - build
          type: approval
          filters: *filter-only-master-and-release
      - deploy:
          filters: *filter-only-master-and-release
          requires:
            - prod-approval
